// Package error provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package error

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code     string    `json:"code"`
	Details  *[]string `json:"details,omitempty"`
	Messagge *string   `json:"messagge,omitempty"`
}
