// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package order

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateOrderDto defines model for CreateOrderDto.
type CreateOrderDto struct {
	CustomerId *string         `json:"customerId,omitempty"`
	Lines      *[]OrderLineDto `json:"lines,omitempty"`
}

// OrderDto defines model for OrderDto.
type OrderDto struct {
	CreateDate *openapi_types.Date `json:"createDate,omitempty"`
	CustomerId *string             `json:"customerId,omitempty"`
	Lines      *[]OrderLineDto     `json:"lines,omitempty"`
	Status     *string             `json:"status,omitempty"`
}

// OrderLineDto defines model for OrderLineDto.
type OrderLineDto struct {
	ProductId *string `json:"productId,omitempty"`
	Quantity  *int64  `json:"quantity,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderDto
