// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package users

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves users based on query
	// (GET /api/users)
	GetApiUsers(c *gin.Context, params GetApiUsersParams)
	// Create user
	// (POST /api/users)
	PostApiUsers(c *gin.Context)
	// Retrieves user based on given ID
	// (GET /api/users/{id})
	GetApiUsersId(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiUsers operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiUsersParams

	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", c.Request.URL.Query(), &params.Username)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter username: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "firstname" -------------

	err = runtime.BindQueryParameter("form", true, false, "firstname", c.Request.URL.Query(), &params.Firstname)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter firstname: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "lastname" -------------

	err = runtime.BindQueryParameter("form", true, false, "lastname", c.Request.URL.Query(), &params.Lastname)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lastname: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiUsers(c, params)
}

// PostApiUsers operation middleware
func (siw *ServerInterfaceWrapper) PostApiUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostApiUsers(c)
}

// GetApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiUsersId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/users", wrapper.GetApiUsers)

	router.POST(options.BaseURL+"/api/users", wrapper.PostApiUsers)

	router.GET(options.BaseURL+"/api/users/:id", wrapper.GetApiUsersId)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUzW7bPBB8FWK/7yhYTnvTLf1JYLRAg9Q+FUZBS2uZqUQyy5VTwdC7F6SsSJYd12nR",
	"k0QuNZydndEOUlNao1Gzg2QHLt1gKcNr5ZDcZOGQ/MqSsUisMNTWihxrWaJfcG0REnBMSufQRKCywbbS",
	"jDmS3y/kmY/IFKHwP+EaEvgv7onFe1ZxT+nen26iQPIFyCbqdszqAVPujg8AjvryJL5fjOe3lF4bfzhD",
	"l5KyrIyGBK7vZuL+49e5UFrcmkLqXDwp3ohbpcUNyRKfDP2ACFixpwFz/xRz/MkQwRbJtTBXk6lnbSxq",
	"aRUk8HYynUwhAit5EwjH0qpWFr/KkY+53CKLRTgRkEj6/VnWVq6t6mpWemIcoL6NQRadzr5jSOCxQqoh",
	"glarfgzR3kEn9RuD3jy76DTqelB/BexneRa1kBeALiMgdNZo1xrjzXTqH6nRjDqILK0tVBrEjB+cv3g3",
	"wFOMpTt4uczX0LtMEsn6eO1Nd9jvl0/BnK4qS0k1JHCPTAq36EQAFivpMBNGi04JlrkfchgbLJsIrHEn",
	"nPOeUDIGkCPv3Bk3NA/hY4WO35msfpVOl6riG/R3KMIMEqYKm6MJXf2zm0/Jko1EPxRrpHATDZIa71TW",
	"vBjXfB9XsarF7MO5zM6yS1LbgoQg+L9GnwOVwVjTE4l4/n3/dST+XPDfGLz3d662qNuGxwPw3yNtO50q",
	"KiCBGJpl8ysAAP//4QZ6sQMHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
