openapi: 3.0.0
info:
   title: Order Service - REST API
   description: Order Service - REST API
   version: 1.0.0
   contact: {}
servers:
-  url: http://localhost:8080/api/v1
paths:
#### Clienti ####
   /orders:
      post:
         summary: Submit order
         description: Submit new order
         operationId: createOrder
        #  parameters:
        #  -  $ref: '#/components/parameters/idGestore'
         requestBody:
            description: New order
            required: true
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/CreateOrderDto'
         responses:
            '201':
               description: Order created
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/CreateOrderDto'
            '400':
               description: Bad request, please check and retry
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '400'
                        messaggio: Bad request, please check and retry
                        dettaglio: [Missing or not valid Field 'fieldName1' , Missing or not valid Field 'fieldName2']
            '500':
               description: Internal server error
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '500'
                        messaggio: An internal server is occurred, please retry
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '401'
                        messaggio: Not authenticated
         tags:
         - order
   /orders/{orderId}:
      get:
         summary: Get order by id
         description: Get order by id
         operationId: getById
         parameters:
         -  name: orderId
            in: path
            required: true
            description: Order Id
            schema:
               type: string         
         responses:
            '200':
               description: Order
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/OrderDto'
            '400':
               description: Bad request, please check and retry
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '400'
                        messaggio: Bad request, please check and retry
                        dettaglio: [Missing or not valid Field 'fieldName1' , Missing or not valid Field 'fieldName2']
            '500':
               description: Internal server error
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '500'
                        messaggio: An internal server is occurred, please retry
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                          $ref: '#/components/schemas/Error'
                     example:
                        codice: '401'
                        messaggio: Not authenticated
         tags:
         - order         
components:
   links: {}
   callbacks: {}
   schemas:
    OrderDto:
      type: object
      properties:
        createDate:
          type: string
          format: date
          example: 2020-10-15
        customerId:
          type: string
          minLength: 1
          maxLength: 10
          example: 10257
        status:
          type: string
          example: pending
        lines:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/OrderLineDto'      
    CreateOrderDto:
      type: object
      properties:
        customerId:
          type: string
          minLength: 1
          maxLength: 10
          example: 102587
        lines:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/OrderLineDto'         
    OrderLineDto:
      type: object
      properties:
        productId:
          type: string
          minLength: 1
          maxLength: 30
          example: Product1
        quantity:
          type: integer
          format: int64
          example: 1
  # Response schemas          
    Error:
      type: object
      properties:
        code:
          type: string
          example: 1
        messagge:
          type: string
          example: An error is occurred
        details:
          type: array
          uniqueItems: true
          items:
           type: string
          example: [Missing or not valid Field 'fieldName1',Missing or not valid Field 'fieldName2']
      required:
        - code
        - message      
   securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
-  name: orders
   description: Orders