openapi: 3.0.0
info:
  title: Title Text
  description: API REST in Golang with Gin Framework
  version: "1.0"
paths:
  /api/users:
    get:
      security:
        - Authorization_Token: []
      description: Get Users
      summary: Retrieves users based on query
      parameters:
        - description: Username
          name: username
          in: query
          schema:
            type: string
        - description: Firstname
          name: firstname
          in: query
          schema:
            type: string
        - description: Lastname
          name: lastname
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/users.User"
  "/api/users/{id}":
    get:
      security:
        - Authorization_Token: []
      description: get User by ID
      summary: Retrieves user based on given ID
      parameters:
        - description: User ID
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users.User"
servers:
  - url: /
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    users.User:
      type: object
      properties:
        firstname:
          type: string
        hash:
          type: string
        id:
          type: integer
        lastname:
          type: string
        role:
          $ref: "#/components/schemas/users.UserRole"
        username:
          type: string
    users.UserRole:
      type: object
      properties:
        id:
          type: integer
        role_name:
          type: string